Version: 1.0.0.4

QuickenedCantripsPerCombat: false

HealingBuffs: true
PotionSickness: false

NerfTavernBrawler: true
NerfStackMaxes: true
NerfSlashingFlourish: false
FixSlashingFlourish: true
FixEarthMyrmidon: true
WildshapeDontDoubleDip: true
NerfVulnerability: true

ScrollsCostSpellSlots: false

InitiativeD12: false